### ISSUE TITLE
Integrity constraint violation: 1048 Column 'body' cannot be null

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#11]
Possible Bug - maybe i can fix it the next days but today im running low in time ;)

_Steps to reproduce:_
- Write a Email to support from extern
- Cron Job will pull Email
- Cron Job will fail s. Stack-Trace

_Possible Solution:_
 App\Jobs\CreateTicketsFromNewEmails while process uses $message-text but
with php-imap library it will be ->textPlain or ->textHtml s. Mailbox.php in vendor folder

```
 if($partStructure->type == 0 && $data) {
                                if(strtolower($partStructure->subtype) == 'plain') {
                                        $mail->textPlain .= $data;
                                }
                                else {
                                        $mail->textHtml .= $data;
                                }
                        }
                        elseif($partStructure->type == 2 && $data) {
                                $mail->textPlain .= trim($data);
                        }
```
_Stack-Trace:_

```
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'body' cannot be null (SQL: insert into `tickets` (`title`, `body$
Stack trace:
#0 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into $
#1 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('insert into `ti...', Arra$
#2 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\Database\Connection->statement('insert into `ti...'$
#3 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert $
#4 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2133): Illuminate\Database\Query\Processors\Processor->processIns$
#5 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->insertGetId(Array, '$
#6 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\Database\Eloquent\Builder->__call('insertGetId'$
#7 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(653): Illuminate\Database\Eloquent\Model->insertAndSetId(Object($
#8 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(522): Illuminate\Database\Eloquent\Model->performInsert(Object(I$
#9 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(284): Illuminate\Database\Eloquent\Model->save()
#10 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(950): Illuminate\Database\Eloquent\Relations\HasOneOrMany->Illuminate\D$
#11 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(285): tap(Object(App\Ticket), Object(Closure))
#12 /home/forge/handesk.vikinks.com/app/Ticket.php(33): Illuminate\Database\Eloquent\Relations\HasOneOrMany->create(Array)
#13 /home/forge/handesk.vikinks.com/app/Jobs/CreateTicketsFromNewEmails.php(34): App\Ticket::createAndNotify(Object(App\Requester), 'New ticket: #1:...', NULL, Array)
#14 /home/forge/handesk.vikinks.com/app/Jobs/CreateTicketsFromNewEmails.php(26): App\Jobs\CreateTicketsFromNewEmails->processMessage(Object(PhpImap\IncomingMail))
#15 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(287): App\Jobs\CreateTicketsFromNewEmails->App\Jobs\{closure}(Object$
#16 /home/forge/handesk.vikinks.com/app/Jobs/CreateTicketsFromNewEmails.php(28): Illuminate\Support\Collection->each(Object(Closure))
#17 [internal function]: App\Jobs\CreateTicketsFromNewEmails->handle(Object(App\Services\Pop3\Mailbox))
````

**Comment by BadChoice** [comment]
I cannot find that `$message->text` usage, I think it uses the `textPlain` everywhere, did you try the last commit?

**Comment by marco-aa** [comment]
I tried the latest commit.

I guess i found the problem.

The Job is using 
`App\Jobs\CreateTicketsFromNewEmails->processMessage(Object(PhpImap\IncomingMail))`

I did a ` Log::info('+++++++++++ '.print_r($message,true));`

and from the print_r i saw in the message object the textPlain is empty and the textHtml contains the html part of the new email.

So the  ` App\Ticket::createAndNotify` will have a empty body and this brings the sql constrain violation.

````
(
    [id] => 42
    [date] => 2017-08-22 13:10:59
    ....
        [messageId] => <35f367e10baae996f29f0199d2b293a4@swift.generated>
    [textPlain] =>
    [textHtml] => <html>
<head>
    <style> 
    ....
 
````

**Comment by BadChoice** [comment]
Oh I see, if no textplain it will fail, and lots of email clients sent only html, I'll add a `getBody()` so it does this

**Comment by BadChoice** [comment]
should be fixed now, if you can try the dev branch, so we can close the issue
Thanks!

**Comment by marco-aa** [comment]
Nearly ;)
 I wrote a html test email form thunderbird with picture - same test-case ...

Now the new ticket is created - but image was missed and i found a error in the log.

```
[2017-08-23 08:02:49] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method App\Services\Pop3\IncomingEmail::getAttachments(
) in /home/forge/handesk.vikinks.com/app/Attachment.php:26
Stack trace:
#0 /home/forge/handesk.vikinks.com/app/Jobs/CreateTicketsFromNewEmails.php(35): App\Attachment::storeAttachmentsFromEmail(Object(App\Services\Pop3\IncomingEmail), Objec
t(App\Ticket))
#1 /home/forge/handesk.vikinks.com/app/Jobs/CreateTicketsFromNewEmails.php(26): App\Jobs\CreateTicketsFromNewEmails->processMessage(Object(App\Services\Pop3\IncomingEma
il))
#2 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(287): App\Jobs\CreateTicketsFromNewEmails->App\Jobs\{closure}(Object(A
pp\Services\Pop3\IncomingEmail), 0)
#3 /home/forge/handesk.vikinks.com/app/Jobs/CreateTicketsFromNewEmails.php(28): Illuminate\Support\Collection->each(Object(Closure))
#4 [internal function]: App\Jobs\CreateTicketsFromNewEmails->handle(Object(App\Services\Pop3\Mailbox))
#5 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /home/forge/handesk.vikinks.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closur
e}()
```

**Comment by BadChoice** [comment]
oops.. ok pull and try again ;)

**Comment by marco-aa** [comment]
Jep looks good :-) Thanks !!!

**Comment by marco-aa** [comment]
I guess i found a smal mistake in 
_https://github.com/BadChoice/handesk/blob/dev/app/Services/Pop3/IncomingEmail.php_

`return strip_tags($this->email->message->textHtml, '<p><a>');`
it should be
`return strip_tags($this->email->textHtml, '<p><a>');`
otherwise it will cause
```
[2017-08-23 11:33:35] production.ERROR: ErrorException: Undefined property: PhpImap\IncomingMail::$message in /home/forge/handesk.vikinks.com/app/Services/Pop3/Incoming
Email.php:14

```

**Comment by marco-aa** [comment]
I saw you fixed it so i'll close this issue :)
