### ISSUE TITLE
Issue - error with ArgvInput.php:265 

### ISSUE THREAD

**Issue by InfinityWebMe** [BadChoice/handesk#218]
Hello,

I installed on my server and the cron job is sending me this error :

```
[2019-01-12 14:18:02] local.ERROR: Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /home/slymprdu/tickets.slym.io/vendor/symfony/console/Input/ArgvInput.php:265)
[stacktrace]
#0 /home/slymprdu/tickets.slym.io/vendor/symfony/console/Input/ArgvInput.php(265): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/slymprdu/...', 265, Array)
#1 /home/slymprdu/tickets.slym.io/vendor/symfony/console/Application.php(1014): Symfony\\Component\\Console\\Input\\ArgvInput->getFirstArgument()
#2 /home/slymprdu/tickets.slym.io/vendor/laravel/framework/src/Illuminate/Console/Application.php(79): Symfony\\Component\\Console\\Application->getCommandName(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#3 /home/slymprdu/tickets.slym.io/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /home/slymprdu/tickets.slym.io/artisan(34): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
```

Any idea why ? 

The front works and i use the branch master. 

Thanks ;)

**Comment by BadChoice** [comment]
php version maybe?

**Comment by InfinityWebMe** [comment]
@BadChoice I use PHP 7.1.25

**Comment by insology** [comment]
Use /usr/local/bin/php instead php in the cronjob, or php-cli if is enable on you server.
Anyway is a php problem ;)
