### ISSUE TITLE
Error while pulling mails

### ISSUE THREAD

**Issue by Sebbito** [BadChoice/handesk#818]
I've set up and installed Handesk as intended but i get errors while pulling mails. Right off the bat: the data I've input is correct since the exact same credentials work in a different helpdesk system.

Contents of the `.env` (edited for confidentiality).

```
MAIL_DRIVER=smtp
MAIL_HOST=selfhosted.mailserver.de
MAIL_PORT=465
MAIL_USERNAME=support@domain.de
MAIL_PASSWORD=password
MAIL_ENCRYPTION=/ssl

MAIL_FETCH_HOST=selfhosted.mailserver.de
MAIL_FETCH_PORT=993
MAIL_FETCH_USERNAME=support@domain.de
MAIL_FETCH_PASSWORD=password
MAIL_FETCH_OPTIONS=/imap
MAIL_FETCH_USE_SSL=true
```

The error I'm getting is the following along with the stack trace:

```
[2023-04-18 09:13:57] local.ERROR: Undefined property: stdClass::$host {"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$host at /var/www/handesk/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:550)
[stacktrace]
#0 /var/www/handesk/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(550): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/handesk/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(606): PhpImap\\Mailbox->getMailHeader()
#2 /var/www/handesk/app/Services/Pop3/Mailbox.php(27): PhpImap\\Mailbox->getMail()
#3 [internal function]: App\\Services\\Pop3\\Mailbox->App\\Services\\Pop3\\{closure}()
#4 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map()
#5 /var/www/handesk/app/Services/Pop3/Mailbox.php(28): Illuminate\\Support\\Collection->map()
#6 /var/www/handesk/app/Jobs/ParseNewEmails.php(30): App\\Services\\Pop3\\Mailbox->getMessages()
#7 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ParseNewEmails->handle()
#8 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#13 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#14 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#17 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#18 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#20 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#21 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#22 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#23 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push()
#24 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#25 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#26 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch()
#27 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(17): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#28 /var/www/handesk/app/Console/Commands/ParseNewEmails.php(14): App\\Jobs\\ParseNewEmails::dispatch()
#29 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\ParseNewEmails->handle()
#30 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#32 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#34 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#35 /var/www/handesk/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#36 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#37 /var/www/handesk/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#38 /var/www/handesk/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /var/www/handesk/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#40 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#41 /var/www/handesk/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#42 /var/www/handesk/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#43 {main}
"} 
```

Any ideas on what went wrong?

**Comment by Sebbito** [comment]
Cleaning up dead Issues an PR's.
